import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
const petstoreVersions = require("./docs/api-reference/versions.json");
const {
  versionSelector,
  versionCrumb,
} = require("docusaurus-plugin-openapi-docs/lib/sidebars/utils")
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  guides: [{type: 'autogenerated', dirName: 'guides'}],
  changelog: [ {type: 'autogenerated', dirName: 'changelogs'}],
  "apireference": [ 
    {
      type: "category",
      label: "Api Reference",
    
      items: require("./docs/api-reference/sidebar"),
    },
  ],
  "api-reference-1.0.0": [
    // {
    //   type: "html",
    //   defaultStyle: true,
    //   value: versionSelector(petstoreVersions),
    //   className: "version-button",
    // },
   
  ],
};


export default sidebars;
