import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
const petstoreVersions = require("./docs/api/versions.json");
const {
  versionSelector,
  versionCrumb,
} = require("docusaurus-plugin-openapi-docs/lib/sidebars/utils")
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  guides: [{type: 'autogenerated', dirName: 'guides'}],
  changelog: [ {type: 'autogenerated', dirName: 'changelogs'}],
  "api-2.0.0": [
    {
      type: "html",
      defaultStyle: true,
      value: versionSelector(petstoreVersions),
      className: "version-button",
    },
   
    {
      type: "category",
      label: "Api Reference",
      link: {
        type: "generated-index",
        title: "Api Reference (latest)",
        description:
          "This is a sample server Piyovi server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
        slug: "/api",
      },
      items: require("./docs/api/sidebar"),
    },
  ],
  "api-1.0.0": [
    {
      type: "html",
      defaultStyle: true,
      value: versionSelector(petstoreVersions),
      className: "version-button",
    },
    {
      type: "category",
      label: "Api Reference",
      link: {
        type: "generated-index",
        title: "Piyovi API (v1.0.0)",
        description:
          "This is a sample server Piyovi server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
        slug: "/api/v1",
      },
      items: require("./docs/api/1.0.0/sidebar"),
    },
  ],
};

console.log(sidebars);

export default sidebars;
